const {test,before,after}=require('node:test'),assert=require('node:assert/strict');
const {initializeApp,deleteApp}=require('firebase-admin/app'),{getFirestore}=require('firebase-admin/firestore');
const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');
const projectId='demo-receiving-guardian';let app,db,env,admin,client;
async function account(email,role){const res=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signUp?key=emulator-only',{method:'POST',signal:AbortSignal.timeout(20000),headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:'synthetic-test-password',returnSecureToken:true})});const u=await res.json();assert.ok(u.idToken,u.error?.message);await db.doc('users/'+u.localId).set({email,role,active:true,companyId:role==='client'?'airali':'__ALL__',companyName:role==='client'?'Airali':'All Companies'});return u;}
async function call(name,data,token){const r=await fetch('http://127.0.0.1:5001/'+projectId+'/us-central1/'+name,{method:'POST',signal:AbortSignal.timeout(20000),headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({data})});return {status:r.status,body:await r.json()};}
before(async()=>{if(!process.env.FIRESTORE_EMULATOR_HOST||!process.env.FIREBASE_AUTH_EMULATOR_HOST)throw Error('Auth and Firestore emulators required');app=initializeApp({projectId},'callable-tests');db=getFirestore(app);env=await initializeTestEnvironment({projectId});await env.clearFirestore();admin=await account('admin-'+Date.now()+'@example.test','admin');client=await account('client-'+Date.now()+'@example.test','client');await db.doc('receivings/r1').set({id:'r1',companyId:'airali',doNumber:'DO1',updatedAt:'original'});});
after(async()=>{await env?.cleanup();await deleteApp(app);});
const payload=()=>({operationId:'http-save-1',id:'d1',base:null,data:{id:'d1',linkedReceivingId:'r1',reportDate:'2026-10-01',doNumber:'DO1',poNumber:'PO1',customer:'Airali',companyId:'airali',sku:'SKU',productName:'Item',expectedQty:2,actualQty:1,issueType:'Damaged',itemCondition:'Damaged',actionTaken:'Return',pic:'Staff',photo:'',resolved:false}});
test('callable denies anonymous and Client mutation with emulator-issued tokens',async()=>{assert.equal((await call('guardianSaveDiscrepancy',payload())).status,401);assert.equal((await call('guardianSaveDiscrepancy',payload(),client.idToken)).status,403);assert.equal((await db.doc('discrepancies/d1').get()).exists,false);});
test('authenticated callable save, duplicate request, delete and restore complete end-to-end',async()=>{
 const first=await call('guardianSaveDiscrepancy',payload(),admin.idToken);assert.equal(first.status,200,JSON.stringify(first.body));assert.equal(first.body.result.verified,true);
 assert.equal((await call('guardianSaveDiscrepancy',payload(),admin.idToken)).status,200);assert.equal((await db.collection('discrepancies').get()).size,1);
 const removal=await call('guardianDeleteRecords',{operationId:'http-delete-1',receiving:[{id:'r1',updatedAt:'original'}],discrepancies:[]},admin.idToken);assert.equal(removal.status,200,JSON.stringify(removal.body));assert.equal((await db.doc('discrepancies/d1').get()).exists,false);
 const restored=await call('guardianRestoreDeletion',{operationId:'http-restore-1',backupId:'http-delete-1'},admin.idToken);assert.equal(restored.status,200,JSON.stringify(restored.body));assert.equal((await db.doc('discrepancies/d1').get()).data().sku,'SKU');
});
test('server rechecks database role even while a previously issued Admin token remains valid',async()=>{await db.doc('users/'+admin.localId).update({role:'client',companyId:'airali',companyName:'Airali'});const r=await call('guardianDeleteRecords',{operationId:'http-denied',receiving:[{id:'r1'}],discrepancies:[]},admin.idToken);assert.equal(r.status,403);assert.equal((await db.doc('receivings/r1').get()).exists,true);});
