const {test}=require('node:test');
const assert=require('node:assert/strict');
const G=require('../guardian.js');
const user={uid:'admin-1',email:'admin@example.test',getIdToken:async()=> 'test-token'};
const admin={email:user.email,role:'admin',active:true,companyId:'__ALL__',companyName:'All Companies'};
const record={id:'r1',doNumber:'DO1',poNumber:'PO1',customer:'Airali',companyId:'airali',shipmentDate:'2026-10-01',vehicleNumber:'ABC123',transportType:'Lorry',expectedQty:10,actualQty:'',arrivalTime:'',startTime:'',completionTime:'',updatedAt:'2026-09-30T01:00:00Z'};
function fixture(options={}){
  const data=new Map([['users/admin-1',structuredClone(admin)]]);let commits=0,attempts=0,reads=0,failReads=0;
  const snap=(path)=>({exists:data.has(path),data:()=>structuredClone(data.get(path)),metadata:{fromCache:false,hasPendingWrites:false}});
  const ref=path=>({path,id:path.split('/').pop(),get:async args=>{assert.equal(args.source,'server');reads++;if(failReads>0&&path!=='users/admin-1'){failReads--;throw G.fault('unavailable','network unavailable');}return snap(path);}});
  const db={collection:c=>({doc:id=>ref(c+'/'+id)}),runTransaction:async fn=>{
    attempts++;if(options.beforeTransaction)await options.beforeTransaction(attempts);
    const writes=[];await fn({get:async r=>snap(r.path),set:(r,d)=>writes.push([r.path,{...data.get(r.path),...d}]),delete:r=>writes.push([r.path,null])});
    if(options.failCommit)throw G.fault('permission-denied','write rejected');
    writes.forEach(([p,d])=>d===null?data.delete(p):data.set(p,d));if(writes.length)commits++;
    if(options.afterCommit)await options.afterCommit(attempts);
  }};
  const auth={currentUser:{...user}};
  const g=G.create({db,auth,sleep:async()=>{},timeoutMs:options.timeoutMs||500});g.setIdentity({...admin,uid:user.uid});
  return {data,ref,g,auth,db,get commits(){return commits;},get attempts(){return attempts;},get reads(){return reads;},set failReads(n){failReads=n;}};
}
const op=f=>({ref:f.ref('receivings/r1'),kind:'receiving',base:null,data:record});
test('admin profile persists through login reads; no profile writes',async()=>{const f=fixture();for(let i=0;i<3;i++)assert.equal((await f.g.readProfile()).role,'admin');assert.deepEqual(f.data.get('users/admin-1'),admin);assert.equal(f.commits,0);});
test('missing or invalid profile cannot infer privileges from email or login hint',async()=>{const f=fixture();f.data.delete('users/admin-1');await assert.rejects(f.g.readProfile(),{code:'guardian/profile-missing'});assert.throws(()=>G.profile({...admin,role:'ADMIN'},user));assert.throws(()=>G.profile({...admin,email:'other@example.test'},user));});
test('client cannot perform receiving edits',async()=>{const f=fixture();const c={...admin,role:'client',companyId:'airali',companyName:'Airali'};f.data.set('users/admin-1',c);f.g.setIdentity({...c,uid:user.uid});await assert.rejects(f.g.commit('Receiving:r1',[op(f)]),{code:'permission-denied'});assert.equal(f.commits,0);});
test('role mutation between read and transaction aborts write without restoring stale admin',async()=>{let f;f=fixture({beforeTransaction:()=>f.data.set('users/admin-1',{...admin,role:'client'})});await assert.rejects(f.g.commit('Receiving:r1',[op(f)]));assert.equal(f.commits,0);assert.equal(f.data.get('users/admin-1').role,'client');});
test('database failure is atomic and never returns success',async()=>{const f=fixture({failCommit:true});await assert.rejects(f.g.commit('Booking:r1',[op(f),{ref:f.ref('booking_slots/s1'),data:{booked:true},slot:true}]),{code:'permission-denied'});assert.equal(f.data.has('receivings/r1'),false);assert.equal(f.data.has('booking_slots/s1'),false);assert.equal(f.g.incidents[0].result,'UNRESOLVED');});
test('temporary write failure retries the immutable request at most three times',async()=>{const f=fixture({beforeTransaction:n=>{if(n<3)throw G.fault('unavailable','retry');}});await f.g.commit('Receiving:r1',[op(f)]);assert.equal(f.attempts,3);assert.equal(f.commits,1);assert.ok(f.g.incidents.some(i=>i.result==='RECOVERED'));});
test('permanent denied write never retries',async()=>{const f=fixture({failCommit:true});await assert.rejects(f.g.commit('Receiving:r1',[op(f)]));assert.equal(f.attempts,1);});
test('lost commit acknowledgement retries without another write',async()=>{const f=fixture({afterCommit:n=>{if(n===1)throw G.fault('unavailable','lost acknowledgement');}});await f.g.commit('Receiving:r1',[op(f)]);assert.equal(f.attempts,2);assert.equal(f.commits,1);});
test('failed verification retains idempotency key; manual retry verifies original record',async()=>{const f=fixture();f.failReads=3;await assert.rejects(f.g.commit('Receiving:r1',[op(f)]));const id=f.data.get('receivings/r1').guardianRequestId;await f.g.commit('Receiving:r1',[op(f)]);assert.equal(f.commits,1);assert.equal(f.data.get('receivings/r1').guardianRequestId,id);});
test('double clicks and hung writes do not unlock another mutation',async()=>{let release;const wait=new Promise(r=>release=r);const f=fixture({timeoutMs:15,beforeTransaction:()=>wait});const first=f.g.commit('Receiving:r1',[op(f)]);await new Promise(r=>setImmediate(r));await assert.rejects(f.g.commit('Receiving:r1',[op(f)]),{code:'guardian/busy'});await assert.rejects(first,{code:'guardian/outcome-unknown'});await assert.rejects(f.g.commit('Receiving:r1',[op(f)]),{code:'guardian/busy'});release();await new Promise(r=>setTimeout(r,10));assert.equal(f.commits,1);assert.equal(f.g.locks.size,0);assert.ok(f.g.incidents.some(i=>i.action==='timeout'&&i.result==='RECOVERED'));});
test('stale frontend update cannot overwrite a concurrent saved edit',async()=>{const f=fixture();f.data.set('receivings/r1',{...record,updatedAt:'newer'});await assert.rejects(f.g.commit('Receiving:r1',[{...op(f),base:record.updatedAt,data:{...record,remarks:'stale'}}]),{code:'guardian/conflict'});assert.equal(f.data.get('receivings/r1').updatedAt,'newer');});
test('invalid quantity/date/status and overwriting milestones are blocked',()=>{for(const v of [-1,NaN,Infinity,null,undefined])assert.throws(()=>G.validate('receiving',{...record,expectedQty:v}));assert.throws(()=>G.validate('receiving',{...record,shipmentDate:'2026-02-30'}));assert.throws(()=>G.validate('receiving',{...record,completionTime:'2026-09-30T02:00:00Z',actualQty:10}));const arrived={...record,arrivalTime:'2026-09-30T01:00:00Z'};assert.throws(()=>G.validate('receiving',{...arrived,arrivalTime:'2026-09-30T01:30:00Z'},arrived));});
test('receiving workflow saves, arrives, starts, completes and allows quantity correction',async()=>{const f=fixture();await f.g.commit('Receiving:r1',[op(f)]);let previous=record;for(const [n,k] of ['arrivalTime','startTime','completionTime'].entries()){const next={...previous,[k]:`2026-09-30T0${n+2}:00:00Z`,updatedAt:String(n),actualQty:10};await f.g.commit('Receiving:r1',[{...op(f),base:previous.updatedAt,data:next}]);previous=next;}await f.g.commit('Receiving:r1',[{...op(f),base:previous.updatedAt,data:{...previous,actualQty:9,updatedAt:'correction'}}]);assert.equal(f.data.get('receivings/r1').actualQty,9);});
test('booking creates slot and receiving together, occupied slot rejects both',async()=>{const f=fixture();f.data.set('booking_slots/s1',{booked:true,receivingId:'someone-else'});await assert.rejects(f.g.commit('Booking:r1',[{ref:f.ref('booking_slots/s1'),slot:true,data:{booked:true}},op(f)]),{code:'guardian/slot-booked'});assert.equal(f.data.has('receivings/r1'),false);});
test('duplicate DO reservation rejects another receiving ID atomically',async()=>{const f=fixture();f.data.set('guardian_do_keys/airali-do1',{receivingId:'r0'});await assert.rejects(f.g.commit('Receiving:r1',[op(f),{ref:f.ref('guardian_do_keys/airali-do1'),claim:true,data:{receivingId:'r1'}}]),{code:'guardian/duplicate'});assert.equal(f.commits,0);});
test('discrepancy validates link and saves independently',async()=>{const f=fixture();const d={...record,reportDate:record.shipmentDate,sku:'SKU1',productName:'Item',issueType:'Damaged',itemCondition:'Damaged',actionTaken:'Return',pic:'Staff',actualQty:9,linkedReceivingId:'r1'};const ops=[{ref:f.ref('discrepancies/d1'),parent:f.ref('receivings/r1'),kind:'discrepancy',data:d}];await assert.rejects(f.g.commit('Discrepancy:d1',ops),{code:'guardian/invalid-link'});f.data.set('receivings/r1',record);await f.g.commit('Discrepancy:d1',ops);assert.equal(f.data.get('discrepancies/d1').sku,'SKU1');});
test('role update and audit either both commit or neither commits',async()=>{const f=fixture({failCommit:true});const ops=[{ref:f.ref('users/staff'),data:{role:'admin'}},{ref:f.ref('guardian_role_audit/a1'),create:true,data:{previousRole:'staff',newRole:'admin'}}];await assert.rejects(f.g.commit('Permissions:staff',ops,{admin:true}));assert.equal(f.data.has('users/staff'),false);assert.equal(f.data.has('guardian_role_audit/a1'),false);});
test('render failure is isolated and logged, no fake recovery',()=>{const f=fixture();f.g.isolate('Calendar',()=>{throw Error('calendar failed');});let ran=false;f.g.isolate('Receiving',()=>ran=true);assert.equal(ran,true);assert.equal(f.g.incidents[0].result,'UNRESOLVED');});
test('token expiry refreshes token once; retries read, never rewrites roles',async()=>{const f=fixture();let calls=0,refreshes=0;f.auth.currentUser.getIdToken=async force=>{assert.equal(force,true);refreshes++;};await f.g.retryRead(async()=>{if(++calls===1)throw G.fault('unauthenticated','expired');return 'ok';});assert.equal(refreshes,1);assert.equal(f.commits,0);});
test('health stays degraded for repeated failed reads and retry limit is bounded',async()=>{const f=fixture();let calls=0;await assert.rejects(f.g.retryRead(async()=>{calls++;throw G.fault('unavailable','offline');},'Database'));assert.equal(calls,3);assert.equal(f.g.health.Database.state,'DEGRADED');});

test('invalid authoritative profile stays unhealthy and cannot be marked recovered',async()=>{const f=fixture();f.data.set('users/admin-1',{...admin,role:'unknown'});await assert.rejects(f.g.readProfile());assert.equal(f.g.health.Authentication.state,'DEGRADED');assert.equal(f.g.incidents[0].result,'UNRESOLVED');});
test('denied client mutation is recorded with no write',async()=>{const f=fixture();const c={...admin,role:'client',companyId:'airali',companyName:'Airali'};f.data.set('users/admin-1',c);f.g.setIdentity({...c,uid:user.uid});await assert.rejects(f.g.commit('Receiving:r1',[op(f)]));assert.equal(f.g.incidents[0].code,'permission-denied');assert.equal(f.g.incidents[0].guardianAction,'CONTAIN_AND_REPORT');assert.equal(f.commits,0);});

test('DO reservation normalization preserves delimiters without collisions',()=>{assert.equal(G.claimKey('airali',' DO/1 '),'airali|do%2F1');assert.notEqual(G.claimKey('a|b','c'),G.claimKey('a','b|c'));assert.notEqual(G.claimKey('a','do/1'),G.claimKey('a','do%2F1'));});
